# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "My eval"

prompts:
  - file://./prompts.txt

providers:
 - "ollama:chat:llama3.2"
 -  "ollama:chat:deepseek-r1:1.5b"
  
tests:
  - file://./tests.csv

