# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "My eval"

prompts:
  - file://./prompts.json

providers:
 - "ollama:chat:llama3.2"
 
# Set up the conversation history
defaultTest:
  vars:
    system_message: 'This is a sample system message'

tests:
  - file://./user_messages.csv

